squiz/quiz/models.py
from django.db import models
from Users.models import Profile


class Test(models.Model):
    quiz_title = models.CharField(max_length=100)
#    timer = models.TimeField(widget=forms.TimeInput(format='%H:%M'))
    student = models.ManyToManyField(Profile, related_name='student')
    teacher = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='teacher')

    def __str__(self):
        return self.quiz_title


class Question(models.Model):
    quiz = models.ForeignKey(Test, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=1000)

    def __str__(self):
        return self.question_text


class Options(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option_text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.option_text


class Score(models.Model):
    quiz = models.ForeignKey(Test, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    student = models.ManyToManyField(Profile)

    def __str__(self):
        return str(self.score)


class Response(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_option = models.CharField(max_length=2000, null=True, blank=True)
    student  = models.ManyToManyField(Profile)

    def __str__(self):
        return self.selected_option

squiz/quiz/views.py
from django.shortcuts import render, redirect
from .models import Test, Question, Options, Score, Response
from Users.models import Profile
from django.contrib.auth.models import User


def quiz_home(request, pk, question_no):
    quiz = Test.objects.get(pk=pk)
    question = Question.objects.get(quiz=quiz, pk=question_no)
    # to get the primary key value of next record(question)
    next_pk = question_no
    for q in Question.objects.filter(quiz=quiz).order_by('-pk'):
        if q.pk > question_no:
            next_pk = q.pk
    quiz.student.add(request.user.profile)
    if request.method == "POST":

        selected_option = request.POST.get('option')
        res = Response.objects.create(question=question, selected_option=selected_option)
        res.student.add(request.user.profile)
        if question_no < quiz.question_set.last().pk:
            # print('/quiz/' + str(pk) + '/' + str(question_no + 1))
            return redirect('/quiz/' + str(pk) + '/' + str(next_pk))
        else:
            return redirect('/quiz/score/' + str(pk) + '/')
    else:
        return render(request, 'quiz/quiz.html', {'question': question})


def evaluate(request, pk):
    quiz = Test.objects.get(pk=pk)
    questions = Question.objects.filter(quiz=quiz)
    sc = 0
    for question in questions:
        user_response = request.user.profile.response_set.get(question=question)
        user_answer = str(user_response.selected_option)
        correct_answer = str(Options.objects.get(question=question, is_correct=True))
        # print("cr- " + str(correct_answer) + "  user- "+ str(user_answer))
        # print("Score- " + str(sc))
        if user_answer == correct_answer:
            sc = sc + 1

    sc = Score.objects.create(quiz=quiz, score=sc)
    sc.student.add(request.user.profile)

    return render(request, 'quiz/quiz_finish.html', {'score': sc})


def add_quiz(request, username):
    user = User.objects.get(username=username)
    prfl = Profile.objects.get(user=user)
    if not prfl.role == "Teacher":
        error_addquiz = True
        return render(request, 'quiz/add_quiz.html', {'error_addquiz': error_addquiz})
    else:
        error_addquiz = False
        if request.method == "POST":
            quiz_title = request.POST.get('quiz_title')
            t = Test.objects.create(quiz_title=quiz_title, teacher=prfl)
            return redirect('/' + str(username) + '/add_quiz/' + str(t.pk) + '/')

        else:
            return render(request, 'quiz/add_quiz.html', {'error_addquiz': error_addquiz})


def add_question(request, username, pk):
    user = User.objects.get(username=username)
    prfl = Profile.objects.get(user=user)

    if not prfl.role == "Teacher":
        error_addques = True
        return render(request, 'quiz/add_question.html', {'error_addques': error_addques})
    else:
        error_addques = False
        quiz = Test.objects.get(pk=pk, teacher=prfl)
        question = Question.objects.filter(quiz=quiz)
        if request.method == "POST":
            question_text = request.POST.get('question_text')
            option1 = request.POST.get('option1')
            option2 = request.POST.get('option2')
            option3 = request.POST.get('option3')
            option4 = request.POST.get('option4')
            correct_ans = request.POST.get('correct_ans')
            ques = Question.objects.create(quiz=quiz, question_text=question_text)
            Options.objects.create(question=ques, option_text=option1)
            Options.objects.create(question=ques, option_text=option2)
            Options.objects.create(question=ques, option_text=option3)
            Options.objects.create(question=ques, option_text=option4)
            ca = Options.objects.get(question=ques, option_text=correct_ans)
            ca.is_correct = True
            ca.save()
            return redirect('/' + str(username) + '/add_quiz/' + str(pk) + '/')

        else:
            return render(request, 'quiz/add_question.html', {'error_addques': error_addques, 'questions': question, 'quiz': quiz})


def show_quiz(request, username, pk):
    user = User.objects.get(username=username)
    prfl = Profile.objects.get(user=user)

    if not prfl.role == "Teacher":
        error_showques = True
        return render(request, 'quiz/show_question.html', {'error_showques': error_showques})
    else:
        error_showques = False
        all_quiz_by_teacher = Test.objects.filter(teacher=prfl)
        quiz = Test.objects.get(pk=pk, teacher=prfl)
        question = Question.objects.filter(quiz=quiz)
        return render(request, 'quiz/show_question.html', {'error_showques': error_showques, 'questions': question, 'all_quiz': all_quiz_by_teacher})


def view_response(request, username, pk):
    user = User.objects.get(username=username)
    prfl = Profile.objects.get(user=user)

    if not prfl.role == "Student":
        error_viewresponse = True
        return render(request, 'quiz/show_response.html', {'error_viewresponse': error_viewresponse})
    else:
        error_viewresponse = False
        quiz = Test.objects.get(pk=pk, student=prfl)
        question = Question.objects.filter(quiz=quiz)
        response = Response.objects.filter(question__quiz=quiz, student=prfl)
        return render(request, 'quiz/show_response.html',
                      {'error_viewresponse': error_viewresponse, 'questions': question, 'responses': response})


def view_result(request, pk):
    quiz = Test.objects.get(pk=pk)
    all_students = quiz.student.all()
    dict = {}
    for t in all_students:
        q = Test.objects.get(pk=pk, student=t)
        dict[t] = t.score_set.get(quiz=q)

    return render(request, 'quiz/view_result.html', {'dict': dict, 'current_quiz': quiz})

squiz/quiz/templates/quiz/add_question.html
{% extends 'Users/base.html' %}
{% load staticfiles %}

{% block  title_extra %}Add Quiz-{% endblock title_extra %}

{% block body_content %}
    {% include 'Users/navbar.html' %}

    {% if error_addques %}
        <div class="container">
                    <div class="card-columns mt-5">
                        <div class="col ml-lg-5">
                            <div class="card text-white bg-dark text-center" style="margin: auto; max-width: 20rem">
                                <div class="card-body">
                                    You must be a student to create quiz!!
                                </div>
                                <div class="card-footer">
                                    <a href="{% url 'Users:home' %}" class="btn btn-success ">Home: </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    {% else %}

        <div class="container-fluid">
        <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-body">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">{{ quiz.quiz_title }}</li>
                                <li class="breadcrumb-item active" aria-current="page">Add Question</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="card-text">
                            <form action="" method="post">
                                {% csrf_token %}
                                 <div class="md-form">
                                    <input type="text" name="question_text" id="form1" class="form-control" required autocomplete="off">
                                    <label for="form1">Question Text</label>
                                </div>
                                <div class="md-form">
                                    <input type="text" name="option1" id="form2" class="form-control" required autocomplete="off">
                                    <label for="form2">Option 1</label>
                                </div>
                                <div class="md-form">
                                    <input type="text" name="option2" id="form3" class="form-control" required autocomplete="off">
                                    <label for="form3">Option 2</label>
                                </div>
                                <div class="md-form">
                                    <input type="text" name="option3" id="form4" class="form-control" required autocomplete="off">
                                    <label for="form4">Option 3</label>
                                </div>
                                <div class="md-form">
                                    <input type="text" name="option4" id="form5" class="form-control" required autocomplete="off">
                                    <label for="form5">Option 4</label>
                                </div>
                                <div class="md-form">
                                    <input type="text" name="correct_ans" id="form6" class="form-control" required autocomplete="off">
                                    <label for="form6">Correct Answer</label>
                                </div>
                                <div class="text-center mb-3">
                                    <button class="submit btn btn-indigo"> Add Quiz </button>
                                </div>
                            </form>

                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card">
                    <div class="card-body">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">Added Questions</li>
                            </ol>
                        </nav>
                            <table class="table table-striped">
                          <tbody>
                          {% for ques in questions %}
                            <tr>
                              <th scope="row">{{ forloop.counter }}</th>
                              <td>{{ ques.question_text }}</td>
                            </tr>
                          {% endfor %}
                          </tbody>
                        </table>



                    </div>
                </div>
            </div>
        </div>
        </div>
    {% endif %}
{% endblock body_content %}

squiz/quiz/templates/quiz/add_quiz.html
{% extends 'Users/base.html' %}
{% load staticfiles %}

{% block  title_extra %}Add Quiz-{% endblock title_extra %}

{% block body_content %}
    {% include 'Users/navbar.html' %}

    {% if error_addquiz %}
        <div class="container">
                    <div class="card-columns mt-5">
                        <div class="col ml-lg-5">
                            <div class="card text-white bg-dark text-center" style="margin: auto; max-width: 20rem">
                                <div class="card-body">
                                    You must be a student to create quiz!!
                                </div>
                                <div class="card-footer">
                                    <a href="{% url 'Users:home' %}" class="btn btn-success ">Home: </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    {% else %}

        <div class="container-fluid">
        <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-body">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active" aria-current="page">Add Quiz</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="card-text">
                        {% if error_quiz_exist %}
                            <span>A quiz with the same name exists!!</span>
                        {% endif %}
                            <form action="{% url 'add_quiz' request.user %}" method="post">
                                {% csrf_token %}
                                 <div class="md-form">
                                    <input type="text" name="quiz_title" id="form1" class="form-control" required autocomplete="off">
                                    <label for="form1">Quiz Title</label>
                                </div>
                                <div class="text-center mb-3">
                                    <button class="submit btn btn-indigo"> Add Quiz </button>
                                </div>
                            </form>

                    </div>
                </div>
            </div>
        </div>
        </div>
    {% endif %}
{% endblock body_content %}

squiz/quiz/templates/quiz/quiz.html
{% extends 'Users/base.html' %}
{% load staticfiles%}

{% block title_extra %}Quiz -{% endblock title_extra %}

{% block body_content %}
    {% include 'Users/navbar.html' %}
    <div class="container-fluid">
        <div class="row">
        <div class="col-md-10 mt-5">
        <div class="card">
          <div class="card-header">
            Question {{ question.id }}.
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ question.question_text }}</h5>
            <form action="{% url 'quiz' question.quiz.pk question.pk %}" method="post">
            {% csrf_token %}
                {% for option in question.options_set.all %}
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="option" id="opt1" value="{{ option.option_text }}">
                  <label class="form-check-label" for="opt1">
                    {{ option.option_text }}
                  </label>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">Submit</button>
            </form>

          </div>
        </div>
        </div>
        <div class="col-md-2 mt-5">
            <div class="card">
                <div class="card-header">
                    {{ question.quiz.quiz_title }}
                </div>
                <div class="card-body">
                <div class="card-title">
                    This Quiz is conducted by {{ question.quiz.teacher.user.first_name}} {{ question.quiz.teacher.user.last_name}}.
                </div>
                    </div>
            </div>
        </div>
        </div>
    </div>
{% endblock body_content %}

squiz/quiz/templates/quiz/show_question.html
{% extends 'Users/base.html' %}
{% load  staticfiles %}

{% block title_extra %}{{ quiz.quiz_title }}-{% endblock title_extra %}

{% block body_content %}
    {% include 'Users/navbar.html' %}
    <div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
        <div class="card">
            <table class="table">
            <thead class="thead-dark">
            <tr>
            <th scope="col">
            <div class="dropdown show " >
            <a class="btn text-white dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   Select Quiz
                </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                {% for quiz in all_quiz %}
                <a href="{% url 'show_quiz'  request.user quiz.pk %}" class="dropdown-item">{{ quiz.quiz_title }}</a>
                {% endfor %}
            </div>
            </div>
            </th>
            <th scope="col">
            {{ current_quiz.quiz_title }}
            </th>
            </tr>
            </thead>
            </table>
            <br>

            {% for question in questions %}
            <div class="card">
              <div class="card-header">
                Question {{ forloop.counter }}.
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ question.question_text }}</h5>
                <br>
                {% for option in question.options_set.all %}
                    <h6>{{ forloop.counter }}. {{ option.option_text }}
                    {% if option.is_correct %}
                    <span class="badge badge-success">Correct</span>
                    {% endif %}
                    </h6>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
        </div>
        </div>
    </div>
    </div>
{% endblock body_content %}

squiz/quiz/templates/quiz/show_response.html
{% extends 'Users/base.html' %}
{% load  staticfiles %}

{% block title_extra %}{{ quiz.quiz_title }}-{% endblock title_extra %}

{% block body_content %}
    {% include 'Users/navbar.html' %}
    <div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
        <div class="card">
            <br>
            {% for question in questions %}
            <div class="card">
              <div class="card-header">
                Question {{ forloop.counter }}.
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ question.question_text }}</h5>
                <br>
                <div class="card-text">Your answer:

                {% for response in responses %}
                    {% if response.question.id == question.id %}
                        {% for option in question.options_set.all %}
                            {% if option.is_correct %}
                                {% if response.selected_option ==  option.option_text %}
                                    <p class="text-success">{{ response.selected_option }}</p>
                                {% else %}
                                    <p class="text-danger">{{ response.selected_option }}</p>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}

                </div>
              </div>
            </div>
            {% endfor %}
        </div>
        </div>
    </div>
    </div>
{% endblock body_content %}

squiz/quiz/templates/quiz/view_result.html
{% extends 'Users/base.html' %}
{% load  staticfiles %}

{% block title_extra %}LeaderBoard-{% endblock title_extra %}

{% block body_content %}
    {% include 'Users/navbar.html' %}
    <div class="container mt-5">
    <div class="row">
        <div class="col-md-8">
        <div class="card">
            <div class="card-header">{{ current_quiz.quiz_title }}</div>
            <br>
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Student Name</th>
                  <th scope="col">Score</th>
                </tr>
              </thead>
              <tbody>
              {% for key, value in dict.items %}

                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td><a href="{% url 'response' key.user.username current_quiz.pk %}">{{ key.user.first_name }}</a></td>
                  <td>{{ value.score }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
        </div>
    </div>
    </div>
{% endblock body_content %}